### ISSUE TITLE
Remote control and wire siren

### ISSUE THREAD

**Issue by sirotkaslo** [nbergont/wofea_v10_hack#2]
Hi,

first thank you for this project. Can you please tell me how do I add my  4 remote controllers? I ordered 4 of the wf-y2. Also I cant seem to turn on the switch for the wired siren. I won't be using any other sensors with this alarm, because I'll use my zigbee aqara sensors to trigger the alarm. 
Thank you!

**Comment by nbergont** [comment]
Hello,

You need to activate receiver dump & debug log, see https://esphome.io/components/remote_receiver.html

Exemple :
```
logger:
  level: DEBUG

remote_receiver:
  pin: GPIO5
  dump: raw # or rc_switch
```
Press on your remote buttons (or move detector) to see RF code on esphome log.
Update substitutions.yaml with your RF codes.

For the wired siren switch : maybe the PCB board change... Try to see if GPIO3 is connected to siren ouput.

Good luck.

**Comment by sirotkaslo** [comment]
Worked like a charm! Thanks!

Just one more question, do you perhaps know why my sensor states are switching between unavailable and the correct state? I can arm the alarm and all remotes work, because I can see the light turning on when I arm it with the remote
![alarm](https://user-images.githubusercontent.com/32062426/77195416-e0cdf000-6ae1-11ea-90df-faaf9e1c7919.png)

log:

[19:44:18][D][switch:021]: 'Arm ext siren' Turning ON.
[19:44:18][D][remote_transmitter:066]: Sending remote code...
[19:44:19][D][binary_sensor:036]: 'Remote arm 1': Sending state OFF
[19:44:20][D][api:067]: Disconnecting Home Assistant 0.107.1 (192.168.1.2)
[19:44:20][D][api.connection:583]: Client 'Home Assistant 0.107.1 (192.168.1.2)' connected successfully!
[19:44:20][D][api:067]: Disconnecting Home Assistant 0.107.1 (192.168.1.2)
[19:44:20][D][api.connection:583]: Client 'Home Assistant 0.107.1 (192.168.1.2)' connected successfully!
[19:44:22][D][api:067]: Disconnecting Home Assistant 0.107.1 (192.168.1.2)
[19:44:22][D][api.connection:583]: Client 'Home Assistant 0.107.1 (192.168.1.2)' connected successfully!

So i guess its constantly disconnecting?

**Comment by sirotkaslo** [comment]
Sorry to bother you, but weird thing is that everything works if I set the logger to VERBOSE, Will try to find whats wrong. Thank you again for your work!

**Comment by nbergont** [comment]
Yes, I have exactly the same probem in lastest esphome version ! 
[See esphome issue here](https://github.com/esphome/issues/issues/877)
[Work arround here](https://github.com/esphome/issues/issues/877#issuecomment-593327174)

It seem that RF reception call interruption very offen and TCP buffer becomes full. Add delay on every loop "fix" the problem (VERBOSE debug have same effect).

I will add this "fix" in repository.

**Comment by sirotkaslo** [comment]
Hi,
just came back to tell you it works great, ZERO issues with the alarm. Using it with the bwalarm and aqara zigbee sensors. Thank you!
