### ISSUE TITLE
wofea v10 is no longer on sale on aliexpress

### ISSUE THREAD

**Issue by ivan-kulikov-dev** [nbergont/wofea_v10_hack#4]
wofea v10 is no longer on sale on aliexpress

instead of esp, arm processor now
https://github.com/ivan-kulikov-dev/wofea_PG105_custom_firmware

**Comment by sirotkaslo** [comment]
Yeah it is: https://www.aliexpress.com/item/32905397433.html?spm=a2g0o.productlist.0.0.73c41323Rks3XF&algo_pvid=062c6339-06a9-4ed3-9e2d-979b7264e77f&algo_expid=062c6339-06a9-4ed3-9e2d-979b7264e77f-0&btsid=0ab6f82215961946268738015e081d&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by ivan-kulikov-dev** [comment]
cool
